-------
Title: Short Course in R: 
Lesson: 2.3: Working with Data Files in R
Date: FEB2021
Author: Jason Gregoire
Contact: jason.gregoire@nps.edu
---------------


# 2.3: Working with Data Files in R

In this lesson, we will discuss the basics of working with data file in R:

* opening and reading various file types
* writing to various file types

In R, we can read data from files stored outside the R environment. We can also write data into files which will be stored and accessed by the operating system. R can read and write into various file formats like **csv**, **excel**, **xml**, **json**, etc.

Some quick housecleaning before we start this lesson. Something that will come up time and time again is the importance of knowing what directory you are working from.

**Getting and Setting the Working Directory**
You can check which directory the R work space is pointing to using the `getwd()`
You can also set a new working directory using `setwd()`

```{R}
# Get and print current working directory.
print(getwd()) 
```

**Note**: If you need to set the working directory, use `setwd("*path*")`  

## File IO: File Types
In general, there are two types of files:

* **Text file** (generic)
  + The content is saved in a text (ASCII) format
  + The content can be viewed by any text editor or word processor
* **Binary file** (specific)
  + The content is saved in an encoded format, e.g., doc, jpeg, gif, etc.
  + The content is viewed by an application that recognizes the encoding, e.g., we can use any application that "understands" the Word doc format to view a Word doc file

In this course, we are going to restrict attention to text files only. But it's important to know R can handle both types. 

## Simple output files: Redirecting program output

In R, reading and writing files can be done by using in-built functions present in R base package. 

### Creating a file
Using `file.create()`, a new file can be created or truncated if it already exists. The function returns a `TRUE` logical value if file is created, otherwise it returns `FALSE`.

*Syntax*: `file.create('')`

* `''`: name of the file is passed in quotes that has to be created

```{R}
# create an empty .txt, .docx, .csv file
`file.create("new_text_file.txt")`
`file.create("new_word_file.docx")`
`file.create("new_csv_file.csv")`
# If not path is provided, R defaults to write files to the current "working" directory (CWD)
```

In R, creating lots of files quickly is made easy. 
To create 100 empty text files: `sapply(paste0("file", 1:100, ".txt"), file.create)`

A new folder, or directory, can similarly be created in R using `dir.create()` 

*syntax*: `dir.create("new_folder")`

```{R}
dir.create("new_folder")
```

### writing content to files

**cat()**
In R, you can write data to a file from the console by redirecting output from `cat()` 

*syntax*: `cat(..., file)`

* `file` specifies the file name to which output has to redirected

```{R}
str = "World"  
# Redirect Output to file  
cat("Hello, ", str, file = "catExample.txt") 
```

**sink()**
You can also use `sink()` to to redirect output from `cat()` and `print()` to a file
*syntax*: `sink(filename)` 

```{R}
# Begin redirecting output 
sink("SinkExample.txt") 
  
x <- c(1, 3, 4, 5, 10) 
print(mean(x)) 
print(class(x)) 
print(median(x)) 
  
sink() 
```

**write.table()**

`write.table()` is used to write an object to a file; it can write a data frame or matrix object to any type of file.

*Syntax*: `write.table(x, file)`

*	* `x`: indicates the object that has to be written into the file
* `file`: indicates the name of the file that has to be written

```{R}
# Write an iris dataset into a txt file 
write.table(x = iris[1:10, ],  
           file = "new_text_file.txt")
```

### Renaming a File
The `file.rename()` function renames the file and returns a logical value. 
The function can rename files, but not directories.

*syntax*: `file.rename(from, to)`

* from: indicates current file name or path
* to: indicates new file name or path

```{R}
# Rename file new_word_file.docx to new_word_file2.docx 
file.rename("new_word_file.docx", "new_word_file2.docx") 
```

### Writing data to CSV files

CSV stands for Comma Separated Values. These files are used to handle large amounts of statistical data. To write data to a .csv file use `write.csv()`

*syntax*: `write.csv(my_data, file = "my_data.csv")`

* `csv()` and `csv2()` are the function in R programming.

```{R}
# Write an iris dataset into a csv file 
write.table(x = iris[5:15, ],  # Write iris dataset into the txt file 
           file = "new_csv_file.csv")  
```

**Note**:

* `write.csv()` uses `'.'` for the decimal point and a comma `(', ')` for the separator.
* `write.csv2()` uses a comma `(', ')` for the decimal point and a semicolon `(';')` for the separator.


### Writing data to Excel files
To write data to excel the `xlsx` package must be installed.

`install.packages("xlsx")`
`library("xlsx")`

*syntax*: `write.xlsx(my_data, file = 'result.xlsx', sheetName = 'my_data', append = FALSE)`


## Reading files in R

When a program is terminated, all data is lost. Storing data in a file preserves data even if the program terminates. Accessing data from files in R across various formats can be accomplished using a few commands in R. 

### Reading a text file
One of the important formats to store a file is in a text file. R provides various methods that one can read data from a text file.

`read.delim()`: 
This method is used for reading “tab-separated value” files (“.txt”). 
By default, point (“.”) is used as decimal points.

*syntax*: `read.delim(file, header = TRUE, sep = “\t”, dec = “.”, …)`

* `file`: the path to the file containing the data to be read into R.
* `header`: a logical value. If TRUE, read.delim() assumes that your file has a header row, so row 1 is the name of each column. If that’s not the case, you can add the argument header = FALSE.
* `sep`: the field separator character. “\t” is used for a tab-delimited file.
* `dec`: the character used in the file for decimal points.

```{R}
# Read a text file 
#myData = read.delim("new_text_file.txt", header = TRUE)  
#print(myData) 
```

**Note**: function assumes file is located in `CWD` unless specified otherwise

### file.choose()

In R, you can select a file interactively using `file.choose()`

```{R}
myFile = read.delim(file.choose(), header = FALSE) # run in R-Studio 
# You will be asked to select a file
# Select "new_text_file.txt"
# print('new_text_file.txt') 
```

### Reading one line at a time
`read_lines()` is used for the reading line of your own choice whether it’s one or two or ten lines at a time. To use this method we have to import `readr` package.

*syntx*: `read_lines(file, skip = 0, n_max = -1L)`

* `file`: file path
* `skip`: Number of lines to skip before reading data
* `n_max`: Numbers of lines to read. If n is -1, all lines in the file will be read.

```{R}
# Import the readr library 
library(readr) 
myData = read_lines("new_text_file.txt", n_max = 1) # 1 line at a time
print(myData) 
myData = read_lines("new_text_file.txt", n_max = 2) # 2 line at a time
print(myData) 
```

### Reading the whole file
`read_file()`: This method is used for reading the whole file. To use this method we have to import reader package.

*syntax*: `read_lines(file)`

* `file`: the file path

```{R}
library(readr) 
myData = read_file("new_text_file.txt") 
print(myData) 
```

### Reading a file in a table format
R provides various methods that one can read data in a tabular format.

**`read.table()`**: read.table() is a general function to read a file in table format. The data will be imported as a R data frame.

*syntax*:`read.table(file, header = FALSE, sep = “”, dec = “.”)`

* `file`: the path to the file containing the data to be imported into R.
* `header`: logical value. If TRUE, read.table() assumes that your file has a header row, so row 1 is the name of each column. If that’s not the case, you can add the argument header = FALSE.
* `sep`: the field separator character
* `dec`: the character used in the file for decimal points.

```{R}
myData = read.table("new.csv.file.csv")  
print(myData) 
```

### read.csv(): 

`read.csv()` is for reading “comma separated value” files (“.csv”) in R. 
**Note**: In this also the data will be imported as a data frame.

*syntax*: `read.csv(file, header = TRUE, sep = “,”, dec = “.”, …)`

* `file`: the path to the file containing the data to be imported into R.
* `header`: logical value. If TRUE, read.csv() assumes that your file has a header row, so row 1 is the name of each column. If that’s not the case, you can add the argument header = FALSE.
* `sep`: the field separator character
* `dec`: the character used in the file for decimal points.

```{R}
myData = read.csv("new.csv.file.csv")  
print(myData) 
```

### read_csv()
`read_csv()`: This method is also used for to read a comma (“,”) separated values values by using the help of `readr` package.

*syntax*: `read_csv(file, col_names = TRUE)`

* `file`: the path to the file containing the data to be read into R.
* `col_names`: Either TRUE, FALSE, or a character vector specifying column names. If * `TRUE`, the first row of the input will be used as the column names.

```{R}
library(readr) 
myData = read_csv("new.csv.file.csv", col_names = TRUE)  
print(myData) 
```

### Reading a file from internet
The functions `read.delim()`, `read.csv()`, and `read.table()` accept URL as a file path and allow import of files from the web.

```{R}
myData = read.delim("http://www.sthda.com/upload/boxplot_format.txt") 
print(head(myData)) 
```

**As always for all matters R, see the online documentation for additional details**

*For a list of all course source materials and references, please see the Course GitHub Repo `Readme.md`*  

## Next lesson: 2.4 Working with Files and Directories in R
