-------
Title: Short Course in R: 
Lesson: 2.2: Packages, Variable Scope, and Namespace in R
Date: FEB2021
Author: Jason Gregoire
Contact: jason.gregoire@nps.edu
---------------

# 2.2: Packages, Variable Scope, and Namespace in R

## Packages in R

Packages in R language are a set of R functions, compiled code, and sample data. 
These are stored under a directory called “library” within the R environment. 
By default, R installs a group of packages during installation. 
Once we start the R console, only the default packages are available by default. 
Other packages that are already installed need to be loaded explicitly to be utilized by the R program that’s using them.

The R foundation maintains a list of R packages here: https://cran.r-project.org/web/packages/available_packages_by_name.html

### Helpful Package-asscoaited funcitons 

* To check available R packages on your local machine use `libPaths()`
* To generate a list of all locally installed packages use `library()`
* To get all packages currently loaded in the active R environment use `search()`

### Install a new package
There are two ways to add R packages. 

* Install directly from the CRAN directory 
* Download the package to your local machine and install manually

To get a packages directly from the CRAN web page use:   
`install.packages("Package Name")`
 
 Example:
 `install.packages("XML")` # Install the package named "XML"

To install a downloaded package use: 
`install.packages(file_name_with_path, repos = NULL, type = "source")`

### Load packages to library
Before a package can be used it must be loaded to the current R environment. 
**Note**: You will also need to load a package that is already installed previously but that is not available in the current environment.

Load the package using:
`library("package Name", lib.loc = "path to library")`

```{R}
# Load the package named "XML"
install.packages("E:/XML_3.98-1.3.zip", repos = NULL, type = "source")
```

## Preliminary Reminders before talking about variable scope and namespace

* **Objects**: everything in R (values, classes, functions, etc.) is an object
* **Objects vs. Names**: names and objects can interact in different ways
  + objects have individuality: multiple names (in multiple scopes) can be bound to the same object
  + two different objects can have the same name (but not in the same scope)
* **Variable assignments do not copy data** - they just bind names to objects (we already talked about this in data structures)
  + *x <- list(10:2)*
  + *y <- x*
* **Deletions of variable names do not delete objects**, they just remove the binding between name and object
  + the statement del(x) removes the binding of x from the name (in the local namespace, more to follow...)


## Varible Scope 
The environment location where we can find and access a variable is called the `scope` of a variable. 
In R, there are two variable scopes:

* **Global**: Global variables exist throughout the execution of a program. It can be changed and accessed from any part of the program.
* **Local**: Local variables exist only within a certain part of a program like a function and are released when the function call ends.

## Global variables
*Global variables* are: 

* Accessible from any part of a program
* Available throughout the lifetime of a program
* Declared external to any function or code block

```{R}
# Global variable  
global = 5 # declaration 
display = function(){ 
  print(global) 
}  
display()  
  
# changing value of global variable's value   
global = 10 
display() 
```

## Local variables
*Local variables* are:

* Defined within a function or block 
* Do not exist outside the block in which they are declared

```{R}
# Local variable   
func = function(){ 
  age = 18 # declaration 
  prinit(age) # <= valid
}  
# print(age) # <= invalid, 'age' can't be accessed outside internal function - error
```

## Variable super assignment in R 
The super assignment operator `<<-` is used within a function to search for a variable in the parent environment frame:

* If not found it keeps on searching the next level until it reaches the global environment 
* If the variable is still not found, it is created and assigned at the global level

```{R}
outer_function = function(){ 
  inner_function = function(){ 
    # Using "<<-" here makes 'a' as global variable 
    a <<- 10
    print(a) 
  } 
  inner_function() 
  print(a) 
} 
outer_function() 
# Variable accessible outside its function 
print(a) 
```

In the above, when the statement `a <<- 10` is encountered within `inner_function()`, it looks for the variable `a` in the `outer_function()` environment. 
When the search fails, it searches in `R_GlobalEnv`. Since `a` is not defined in this global environment as well, it is created and assigned there.

## Dealign with Namespace Conflict in R

If you’ve used R for any length of time, you’ve probably run into naming conflicts. 

Some of the results can be rather subtle, leading to puzzling errors. 

*Example with the `dplyr` package* 

```{R}
library(dplyr)
iris %>%
  group_by(Species) %>%
  summarize(Mean.Sepal.Length=mean(Sepal.Length))
```
  
The above example with `summarize()` should produce this:
     Species Mean.Sepal.Length
1     setosa             5.006
2 versicolor             5.936
3  virginica             6.588

But it might produce this:
*Error in summarize(., Mean.Sepal.Length = mean(Sepal.Length)): argument "by" is missing, with no default*

In this case, two R packages (`dplyr` & `Hmisc`) have functions that share the same namespace. 

When you loaded the libraries the installer produced the message:

The following objects are masked from 'package:dplyr': `combine`, `src`, `summarize`

*R is telling you that summarize, along with some other functions, no longer refer to the functions in dplyr, but instead refer to the functions in Hmisc.*

### Finding namespace conflicts

R easily lets you identify what environment your system is defaulting to by using `environment(summarize)` and what functions are in conflict by using `conflicts()` 

```{R}
library(dplyr)
library(Hmisc)
environment(summarize)
conflicts()
```

You can also use `library()` to list all available packages, which also lists conflicts.

```{R}
library()
```

**Note**: Because `summarize` from `Hmisc` operates differently than `summarize` in `dplyr`, you may get the error above.

### Namespace functions

When there are conflicts, **Namespace functions** are used in R to differentiate between functions that share a namespace from differing packages

In R, `namespace`  works with two operators:

* *double colon* `::`
* *triple colon* `:::`

**syntax**: `Package::function()`

```{R}
iris %>%
  group_by(Species) %>%
  dplyr::summarize(Mean.Sepal.Length=mean(Sepal.Length))
```

```{R}
library(dplyr)
library(Hmisc)
x <- c(1,2,3,4)
y <- c("a","b","c","d")
df <- data.frame(x,y)
a <- Hmisc::summarize(x,y,sum)   # using Hmisc 
print(a)
```

```{R}
a <- dplyr::summarize(df,sum_value = sum(x))  # using dplyr    
print(a)
```

**As always for all matters R, see the online documentation for additional details**

*For a list of all course source materials and references, please see the Course GitHub Repo `Readme.md`*  

## Next lesson: 2.3 Working with Data Files in R




