-------
Title: Short Course in R: 
Lesson: 4.3: Access and Use ExternalDBs with SQL in R
Date: FEB2021
Author: Jason Gregoire
Contact: jason.gregoire@nps.edu
---------------

# 4.3: Access and Use ExternalDBs with SQL in R

So far, we have dealt with small datasets that easily fit into your computer's memory. But what about datasets that are too large for your computer to handle as a whole? 

In this case, storing the data outside of R and organizing it in a database is often necessary and many large datasets are already available in public or private databases. You can even query them without having to download the data first.

R can connect to almost any existing database type. In R you can use `dplyr` in conjunction with `dbplyr` to connect to the widely-used open source databases such as `sqlite`, `mysql`, `postgresql`and Google’s `bigquery`.

Interfacing with databases using `dplyr` focuses on retrieving and analyzing datasets by generating SELECT SQL statements, but it doesn't modify the database itself. `dplyr` does not offer functions to `UPDATE` or `DELETE` entries. If you need these functions, you will need to use additional R packages such as `RSQLite`. 


`install.packages(c("dbplyr", "dplyr", "RSQLite"))`

```{R}
library(dplyr)
library(dbplyr)
library(RSQLite)
```

For our work with SQl, we will use a SQLite database that is contained in a single file `portal_mammals.sqlite` 

```{R}
dir.create("data_raw", showWarnings = FALSE)
download.file(url = "https://ndownloader.figshare.com/files/2292171",
              destfile = "data_raw/portal_mammals.sqlite", mode = "wb")
```

## Connecting to databases
```{R}
library(dplyr)
library(dbplyr)
```

Point R to the database

```{R}
mammals <- DBI::dbConnect(RSQLite::SQLite(), "data_raw/portal_mammals.sqlite")
```


This command uses 2 packages that helps dbplyr and dplyr talk to the SQLite database. DBI is not something that you'll use directly as a user. It allows R to send commands to databases irrespective of the database management system used. The RSQLite package allows R to interface with SQLite databases.

This command does not load the data into the R session (as the read_csv() function did). Instead, it merely instructs R to connect to the SQLite database contained in the portal_mammals.sqlite file.

Let's take a closer look at the mammals database.

```{R}
src_dbi(mammals)
```         

Just like a spreadsheet with multiple worksheets, a SQLite database can contain multiple tables. In this case three of them are listed in the tbls row in the output above:

* plots
* species
* surveys

### Querying the database with the SQL syntax
To connect to tables within a database, you can use the `tbl()` function from `dplyr`. This function can be used to send SQL queries to the database. To demonstrate this functionality, let's select the columns "year", "species_id", and "plot_id" from the surveys table:

```{r}
tbl(mammals, sql("SELECT year, species_id, plot_id FROM surveys"))
```

### Querying the database with the `dplyr` syntax
One of the strengths of `dplyr` is that the same operation can be done using dplyr's verbs instead of writing SQL. First, you select the table on which to do the operations by creating the surveys object, and then you use the standard dplyr syntax as if it were a data frame:

```{R}
surveys <- tbl(mammals, "surveys")
surveys %>%
    select(year, species_id, plot_id)
```

In this case, the surveys object behaves like a data frame. Several functions that can be used with data frames can also be used on tables from a database. For instance, the head() function can be used to check the first 10 rows of the table:

```{R}
head(surveys, n = 10)
```

This output of the head command looks just like a regular data.frame: The table has 9 columns and the head() command shows us the first 10 rows. 

**Note**: that the columns plot_type, taxa, genus, and species are missing. These are now located in the tables plots and species which we will join together in a moment.

However, some functions don't work quite as expected. For instance, let's check how many rows there are in total using `nrow()`:

```{R}
nrow(surveys)
```

**Note**: In this example, R doesn't know how many rows the surveys table contains - it returns NA instead. This results because the data is not loaded in memory ... more on this in the next section. 

## SQL translation
Relational databases typically use a special-purpose language, Structured Query Language (SQL), to manage and query data.

For example, the following SQL query returns the first 10 rows from the surveys table:

* `SELECT` `*`
* `FROM` `surveys`
* `LIMIT` `10`

Behind the scenes, `dplyr`:

* translates your R code into SQL
* submits it to the database
* translates the database's response into an R data frame

To lift the curtain, we can use dplyr's `show_query()` function to show which SQL commands are actually sent to the database:

```{R}
show_query(head(surveys, n = 10))
```

The output shows the actual SQL query sent to the database; it matches our manually constructed SELECT statement above.

Instead of having to formulate the SQL query ourselves - and having to mentally switch back and forth between R and SQL syntax - we can delegate this translation to dplyr. (You don't even need to know SQL to interact with a database via dplyr!)

dplyr, in turn, doesn't do the real work of subsetting the table, either. Instead, it merely sends the query to the database, waits for its response and returns it to us.

That way, R never gets to see the full surveys table - and that's why it could not tell us how many rows it contains. This is by design as this allows us to work with large datasets - even those too large to fit into our computer's memory.

dplyr can translate many different query types into SQL allowing us to, e.g., select() specific columns, filter() rows, or join tables.

### Simple database queries

First, let's only request rows of the surveys table in which weight is less than 5 and keep only the species_id, sex, and weight columns.

```{R}
surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)
```

**Note**: The last line reads ```... with more rows`

### Laziness (reource conservation)

When working with databases, dplyr and R in general performs lazy evaluation.

* It never pulls data into R unless you explicitly ask for it.
* It delays doing any work until the last possible moment - it collects together everything you want to do and then sends it to the database in one step.

### Piping

When you construct a `dplyr` query, you can connect multiple verbs into a single pipeline. 
For example, we combined the `filter()` and `select()` verbs using the `%>%` pipe.

If we wanted to, we could add on even more steps, e.g. remove the *sex column* in an additional select call:

```{R}
data_subset <- surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)

data_subset %>%
  select(-sex)
```

Just like the first select(species_id, sex, weight) call, the select(-sex) command is not executed by R. It is sent to the database instead. Only the final result is retrieved and displayed.

To instruct R to retrieve all of the query results from the database, add `collect()` to the pipe. 

```{R}
data_subset <- surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight) %>%
  collect()
```

**Note**: all 17 rows that match our query are returned. 

### Complex database queries
`dplyr` enables database queries across one or multiple database tables, using the same single- and multiple-table commands regardless if the the data is remote or local! 

**Joins**
```{R}
plots <- tbl(mammals, "plots")
plots
```

The plot_id column also features in the surveys table:

```{}
surveys
```

Because `plot_id` is listed in both tables, you can use it to look up matching records, and join the two tables.

If you have two tables named x and y with a common column called "ID", we can join them using 'join' functions, two of which are described and illustrated below.

`inner_join()`: This returns all rows from x where there are matching values in y, and all columns from x and y.

`left_join()`: This return all rows from x, and all columns from x and y. Rows in x with no match in y will have NA values in the new columns.

In both forms of join, if there are multiple matches between x and y, all combinations of the matches are returned. For the full list of 'join' functions, check out the tidyverse join page.

To extract all surveys for the first plot, (plot_id 1):

```{R}
plots %>%
  filter(plot_id == 1) %>%
  inner_join(surveys) %>%
  collect()
```

**Note**: Without the `collect()` statement, only the first 10 matching rows are returned. By adding `collect()`, the full set of 1985 is retrieved.

Total number of rodents observed in each plot in each year.

```{R}
# With dplyr syntax
species <- tbl(mammals, "species")

left_join(surveys, species) %>%
  filter(taxa == "Rodent") %>%
  group_by(taxa, year) %>%
  tally %>%
  collect()
#> Joining, by = "species_id"

# With SQL syntax
query <- paste("
SELECT a.year, b.taxa,count(*) as count
FROM surveys a
JOIN species b
ON a.species_id = b.species_id
AND b.taxa = 'Rodent'
GROUP BY a.year, b.taxa",
sep = "" )

tbl(mammals, sql(query))
```

### Creating a new SQLite database
With R you can create a new database.
To recreate the mammals database download and read the csv files. 

```{R}
download.file("https://ndownloader.figshare.com/files/3299483",
              "data_raw/species.csv")
download.file("https://ndownloader.figshare.com/files/10717177",
              "data_raw/surveys.csv")
download.file("https://ndownloader.figshare.com/files/3299474",
              "data_raw/plots.csv")
library(tidyverse) # For the read_csv() function
species <- read_csv("data_raw/species.csv")
```

```{R}
surveys <- read_csv("data_raw/surveys.csv")
```

```{R}
plots <- read_csv("data_raw/plots.csv")
```

Creating a new SQLite database with dplyr is easy. You can re-use the same command we used above to open an existing `.sqlite` file. The `create = TRUE` argument instructs R to create a new, empty database instead.

Caution: When `create = TRUE` is added, any existing database at the same location is overwritten without warning.

```{R}
my_db_file <- "data_raw/portal-database-output.sqlite"
my_db <- src_sqlite(my_db_file, create = TRUE)
```

Currently, the new database is empty, it doesn't contain any tables:

```{R}
my_db
```

To add tables, copy the existing data.frames into the database one by one:

```{R}
copy_to(my_db, surveys)
copy_to(my_db, plots)
my_db
```

If you check the location of our database you'll see that data is automatically being written to disk. 


**As always for all matters R, see the online documentation for additional details**

*For a list of all course source materials and references, please see the Course GitHub Repo `Readme.md`*  

## This is the final lesson in our R short course! Congrats on sticking with it!